# Generated by Django 5.2.15 on 2026-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_confirmed_at_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("razorpay", "Razorpay"),
                    ("stripe", "Stripe"),
                    ("cash_on_delivery", "Cash on delivery"),
                ],
                default="razorpay",
                max_length=40,
            ),
        ),
    ]
