# Generated by Django 5.2.15 on 2026-06-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_authotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium_member",
            field=models.BooleanField(default=False),
        ),
    ]
