# Generated by Django 5.2.15 on 2026-06-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_birth_date_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_choice",
            field=models.CharField(
                choices=[
                    ("fox", "Fox"),
                    ("panda", "Panda"),
                    ("tiger", "Tiger"),
                    ("cat", "Cat"),
                    ("dog", "Dog"),
                    ("owl", "Owl"),
                    ("lion", "Lion"),
                    ("bear", "Bear"),
                    ("rabbit", "Rabbit"),
                    ("frog", "Frog"),
                    ("koala", "Koala"),
                    ("penguin", "Penguin"),
                    ("unicorn", "Unicorn"),
                    ("rocket", "Rocket"),
                    ("star", "Star"),
                    ("sun", "Sun"),
                    ("moon", "Moon"),
                    ("leaf", "Leaf"),
                    ("bolt", "Bolt"),
                    ("smile", "Smile"),
                ],
                default="smile",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
