# Generated by Django 5.2.15 on 2026-06-27 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomepageBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=240)),
                ("badge", models.CharField(blank=True, max_length=80)),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "desktop_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="homepage-banners/"
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="homepage-banners/mobile/"
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("accent", models.CharField(default="violet", max_length=32)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
