# Generated by Django 5.2.15 on 2026-06-27 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommercePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipping_fee_amount",
                    models.DecimalField(decimal_places=2, default=49, max_digits=12),
                ),
                (
                    "premium_free_shipping_threshold",
                    models.DecimalField(decimal_places=2, default=200, max_digits=12),
                ),
                (
                    "non_premium_free_shipping_threshold",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "premium_membership_annual_fee",
                    models.DecimalField(decimal_places=2, default=500, max_digits=12),
                ),
                (
                    "premium_membership_duration_days",
                    models.PositiveIntegerField(default=365),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
    ]
